name: Binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  
  cpu_linux_build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: | 
          sudo apt-get update 
          sudo apt-get install -y \
            uuid-dev \
            build-essential  
      - name: Build
        run: make OS=LINUX compiler=g++ COMPILER_TYPE=GNU
      - name: Prepare to upload binary
        run: |
          mkdir -p Binaries
          cp quest_link Binaries/.
      - uses: actions/upload-artifact@v1
        with:
          name: linux_quest_link
          path: Binaries
          
  cpu_macos_build:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make OS=MACOS compiler=clang COMPILER_TYPE=CLANG
      - name: Prepare to upload binary
        run: |
          mkdir -p Binaries
          cp quest_link Binaries/.
      - uses: actions/upload-artifact@v1
        with:
          name: macos_quest_link
          path: Binaries

  cpu_windows_build:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: build
        shell: cmd
        run: make OS=WINDOWS COMPILER=cl COMPILER_TYPE=MSVC WINDOWS_ARCH=64
      - name: Prepare to upload binary
        run: |
          mkdir -p Binaries
          cp windows_quest_link.exe Binaries/.
      - uses: actions/upload-artifact@v1
        with:
          name: windows_quest_link.exe
          path: Binaries

  publish_binaries:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: linux_quest_link
          path: Binaries
      - uses: actions/download-artifact@master
        with:
          name: macos_quest_link
          path: Binaries
      - uses: actions/download-artifact@master
        with:
          name: windows_quest_link.exe
          path: Binaries
      - name: Testing that the binaries were downloaded!
        run: ls