name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  cpu_windows_build:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: -h
      - name: prepare build
        shell: cmd
        run: choco install make
      - name: debug (gen files)
        shell: cmd
        run: | 
          cl -O2 -EHs -DQuEST_PREC=2 -nologo -DDWIN32 -D_WINDOWS -FoQuEST.o \
          -IQuEST/include -IQuEST/src/CPU -IQuEST/src -IWSTP/Windows -ILink -c QuEST/src/QuEST.c 
      - name: debug (view files)
        shell: cmd
        run: dir
      - name: build
        shell: cmd
        run: make OS=WINDOWS COMPILER=cl COMPILER_TYPE=MSVC
    
  cpu_linux_build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dependencies
        run: | 
          sudo apt-get update 
          sudo apt-get install -y \
            uuid-dev \
            build-essential
      - name: build
        run: make OS=LINUX compiler=g++ COMPILER_TYPE=GNU

  cpu_macos_build:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make OS=MACOS compiler=clang COMPILER_TYPE=CLANG
