name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  cpu_windows_build:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: build
      run: make OS=WINDOWS COMPILER=cl COMPILER_TYPE=MSVC
    
  cpu_linux_build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: make OS=LINUX compiler=g++ COMPILER_TYPE=GNU

  cpu_macos_build:
    name: MacOS
    runs-on: macOS-latest
    steps:
      - name: build
        run: make OS=MACOS compiler=clang COMPILER_TYPE=CLANG
