name: Linux

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  cpu_linux_build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: | 
          sudo apt-get update 
          sudo apt-get install -y \
            uuid-dev \
            build-essential
            
      - name: Build
        run: make OS=LINUX compiler=g++ COMPILER_TYPE=GNU
        
      - name: Prepare to upload binary
      - run: |
          mkdir -p Binaries
          cp quest_link Binaries/.
      
      - uses: actions/upload-artifact@v1
        with:
          name: linux_quest_link
          path: Binaries